defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

[kubernetes]
  exposedByDefault = false


# enabling api is not absolutely necessary, it is needed only if you need dashboard.
[api]
  dashboard = true
  entrypoint = "dashboard"


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


  [entryPoints.dashboard]
  address = ":8080"

    [entryPoints.dashboard.auth.basic]
    usersFile = "/secrets/dashboard-users.htpasswd"


[acme]
OnHostRule = true
email = "kamran@wbitt.com"
storage = "/acme/acme.json"
entryPoint = "https"

# CA server to use.
# Uncomment the 'caServer' line to use Let's Encrypt's staging server,
#   leave commented to goto/use prod certificates.
#
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

  [acme.httpChallenge]
  entryPoint = "http"



